wallet:
  transaction_signup: Signup
  transaction_commit: Commit
  signup_amount: 500
  subscription_amount: 150
  challenge_subscription: Challenge Subscription

round:
  states: 
    inactive: inactive
    open: open
    close: close

repository:
  popular: 
    stars: 25
  max_size: 100

user:
  :royalty_points_threshold: 50_000

sponsor:
  individual:
    base: 5
  organization:
    base: 250

scoring_engine:
  :repositories: 'repositories' # repositories dir
  :max_score: 5
  :code_lines_to_points: 10
  :code_change_threshold: 200
  :code_change_threshold_score: 1
  :comments_to_points: 3
  :commit_comments_weightage: 0.1
  :commit_default_weightage: 0.45
  :bugspot_weightage: 0.45
  :bugspot_scores_threshold: 2

subscriptions:
  free: 20
  individual: 10
  organization: 10

redeem:
  min_points: 100
  one_dollar_to_points: 10
  retailers:
    - github
    - amazon
    - other
  github_redeem_amounts: 
    - 10
    - 25
    - 50
    - 100 
  amazon_stores:
    - amazon.com
    - amazon.in
    - amazon.uk

