wallet:
  transaction_signup: Signup
  transaction_commit: Commit
  signup_amount: 500
  subscription_amount: 150
  challenge_subscription: Challenge Subscription

repository:
  popular:
    stars: 25
  max_size: 100

redeem_request_threshold:
  free: 400
  paid: 500

organizational_sponsorers:
  josh:
    logo: "org-josh-logo.png"
    link: "http://www.joshsoftware.com"
  ett:
    logo: "org-ett-logo.png"
    link: "https://www.facebook.com/Emerging-Technology-Trust-840341759454971/"

scoring_engine:
  :repositories: 'repositories' # repositories dir
  :max_score: 5
  :code_lines_to_points: 10
  :code_change_threshold: 200
  :code_change_threshold_score: 1
  :comments_to_points: 3
  :commit_comments_weightage: 0.1
  :commit_default_weightage: 0.45
  :bugspot_weightage: 0.45
  :bugspot_scores_threshold: 2
  :frequency_factor_threshold: 30

redeem:
  min_amount: 5
  one_dollar_to_points: 10
  retailers:
    - github
    - amazon
    - other
  github_redeem_amounts:
    - 10
    - 25
    - 50
    - 100
  amazon_stores:
    - amazon.com
    - amazon.in
    - amazon.uk

account:
  twitter: 'https://twitter.com/code_curiosity'
