home:
  -
    question: Who should use CodeCuriosity?
    answer: Everyone who contributes to open source. It's not only fun, but you're also making a difference!
  -
    question: How does CodeCuriosity benefit me?
    answer: You earn points for contributions. You can redeem points for rewards. You're contributing back to the community!
  -
    question: How does it work?
    answer: Set a monthly goal for yourself and earn points. Redeem points and buy something from the GitHub Shop!
  -
    question: I'm a newbie. What's in it for me?
    answer: If you need a push to start contributing, this is it! You not only build your profile, you earn points and you're contributing back.
faq:
  -
    question: What is CodeCuriosity?
    answer: CodeCuriosity is a platform that encourages contributions to open source. Everyone is rewarded for their efforts, no matter how big or small they are. This is not a "winner takes all" competition. CodeCuriosity rewards code commits, opening or commenting on issues and even consistency in open source contribution. In short, we create healthy competition among contributors that gives them the incentive to contribute. Our aim is to make open source contribution a habit!
  -
    question: Who should use CodeCuriosity?
    answer: Everyone who contributes to open source. It's not only fun but you're also making a difference! Since all commits are rewarded and everyone (experts and newbies alike) is rewarded, it's always encouraging. There are so many repository owners that are looking out for help from developers and CodeCuriosity not only helps you help others but also rewards you while doing it. It's about having your cake and eating it too!.
  -
    question: How does CodeCuriosity benefit me?
    answer: You earn points for contributions. You can redeem points for rewards. You're contributing back to the community! This helps you build your open source profile, helps your organization recognize your hard work, helps you contribute back to the the community and also helps you to learn new things and get advice from the community - not to mention it's very satisfying.
  -
    question: How does it work?
    answer: We gamify open source contributions. Your only task is to sign-up with your GitHub account on CodeCuriosity. After that, we do the rest! The system analyses your commits and activities and they are automatically scored and shown on your dashboard. Everyone and everything is rewarded. You can choose your monthly goal when you log in and try to achieve it. Every month-end, the cumulative scores are added to your wallet and if you have achieved your goal, you get bonus points!
  -
    question: What are points and how do they work?
    answer: Points are the scores you have accumulated for your contributions. You can redeem these points for digital goods, currently on the Github Shop. We send you a gift-card of the amount you want and you can redeem that at the store!
    html_anchor: 'what-are-points'
  -
    question:  How do I redeem my points?
    answer: Redemptions are in the form of digital prizes or Github Merchandise or Company sponsored swag. You need to accumulate at least 100 points before you can redeem them. <span style='color:red'>Please note that you have to be registered on Github for at least 6 months and on CodeCuriosity for at least 3 months before you can redeem any points. In any month, you can redeem at most 500 Royalty points. </span>
  -
    question:  How long does the redemption process take?
    answer: Usually, we redeem points within 1 or 2 days. All redemption requests are screened by our fraud detection team. We have come across cases of fraud (unfortunately) where users were trying to manipulate the system to make money in unfair ways. We have ejected these users from the system. <i style='color:blue'>This is indeed a sign that the initiative has been sucessful </i> :) If your redemption request is not processed within 4 days, please contact us and we shall discuss the reasons behind the delay.
  -
    question: Ok. I bought the concept. But how do I start? This is all new to me!
    answer: "Don't worry! Start with <a href='http://codetriage.com' target='_blank'>Code Triage</a>. It's a very good way to choose which language and repositories you want to contribute to. It sends you some GitHub issues that you can look at everyday! Too complex for you? Start by reading and contributing back some documentation at <a href='http://www.codetriage.com' target='_blank'>Code Triage</a> by clicking on the 'Triage Docs' button after chooosing a repository."
  -
    question: I'm a newbie. What's in it for me?
    answer: If you need a push to start contributing, this is it! You not only build your profile, you earn points and you're contributing back.
  -
    question: How do I signup?
    answer: You can signup using your GitHub account and it's free.
  -
    question: Can I leave CodeCuriosity?
    answer: We would be really sad to see you go. However, if you still want to leave, you can 'Delete Account' in the profile settings. You may also want to search for the CodeCuriosity Application in Github applications and revoke access. You can do this from your <a href='https://github.com/settings/applications' target='_blank'>Github Applications.</a> Of course, you are welcome to sign-up again and re-activate your account.
  -
    question: Why only Github? Why not BitBucket or GitLab or any other open-source systems?
    answer: We believe that Github is the centre of the universe and we do hope Github shows us the same love back! Having said that, we believe that most of the open-source contributions happen on Github and it helps to take baby steps. If we see a definite need to integrate with others, we shall do that in the far future!
  -
    question: Can I add any repository?
    answer: No. It's important that we stick to "valuable contributions". You are *not* rewarded for adding commits to your test repository! You will be able to see only those repositories that have more than 25 stars or whose origin (i.e. from where your forked it) has 25 stars.
  -
    question: Why aren't all my own or forked repositories showing up?
    answer: There could be couple of reasons - The origin repository of your forked repository may not have sufficient stars or it is syncing in the background and may take sometime to reflect.
  -
    question: How are past contributions rewarded?
    answer: When a user signs up, CodeCuriosity profiles the user's and the user's owned repositories. For every repository that has more than 25 stars, a royalty bonus is credited based on a factor of number of stars and number of followers. Organization contributions are not counted (yet) and commits as collaborator to another repository is not counted.
  -
    question: How is the scoring done?
    answer: The scoring is done automatically using an algorithm based on certain criteria. For example, is the commit in the critical path, does it fix an issue, the number of lines committed, the expertize of the user etc. This is always evolving and ideas are welcome. These scores can be over-ridden by langauge or domain experts as and when required.
  -
    question: When is the scoring done?
    answer: Scoring is done continuously but the results may take some time to show. Every month-end, your wallet gets credited with the cumulative scores. If you have achieved your month's goal, your bonus points get credited to your wallet!
  -
    question: What is scored?
    answer: Automated scoring is done on commits, comments, opening an issue and closing an issue today. As we evolve, this may get more streamlined and we may include other factors too.
  -
    question: Can I make real money from CodeCuriosity?
    answer: Not yet ;) It is our aim to sort out legal issues and if we get enough grants and contributions from the community, we would be more than happy to reward open source contributions with money. We dream to invent a new career - A full-time open source contributor who works for the community and not for a company!
  -
    question: How does CodeCuriosity sustain? What keeps is it going?
    answer: Currently, we at Josh Software, keep it going. We would love to get some support from companies who support this cause. We would love to have companies like <a href="http://github.com">GitHub</a>, <a href="https://www.mozilla.org/en-US/foundation">Mozilla</a> and others provide us grants to take this initiative to greater heights. What is critical is that grants are for ALL open source repositories equally - we do not believe in grants for specific repositories and we shall never allow that!
  -
    question: Do companies or organisations benefit from CodeCuriosity?
    answer: Yes. We are in the process of giving a cumulative score to organisations that the github users belongs to. So, if you are working in a company that encourages you to contribute to open-source, the organization overall rating increases too! This is an algorithm that uses a weighted average of it's employees scores. This not only helps the organization get a better profile but also encourages developers to join such companies!
